name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          
      - name: Enable APIs
        run: |
          gcloud services enable run.googleapis.com
          gcloud services enable cloudresourcemanager.googleapis.com
          gcloud services enable aiplatform.googleapis.com
          
      - name: Build and push container
        run: |
          gcloud builds submit --tag gcr.io/vc-interview-agent/vc-interview-platform
          
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'vc-interview-platform'
          image: 'gcr.io/vc-interview-agent/vc-interview-platform'
          region: 'us-central1'
          flags: '--allow-unauthenticated --port=8080'
